server:
  port: 7001

spring:
  application:
    name: mirco-weather-eureka-client-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间,适用于网络状况正常的情况下,两端连接所用的时间
  ConnectTimeout:  5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
logging:
  level:
    # feign日志以什么级别监控那个接口
    com.ponking.springcloud.service.PaymentFeignService: debug